name: 'setup-go-c8y-cli'
description: 'Cache and install the go-c8y-cli binary (c8y) to $PATH'
author: reubenmiller
inputs:
  version:
    required: false
    description: go-c8y-cli version to setup
    default: latest
  showVersion:
    required: false
    description: Show cli version
    default: "true"
  showTenant:
    required: false
    description: Show tenant information
    default: "true"
runs:
  using: 'node16'
  main: 'dist/index.js'
