name: 'setup-go-c8y-cli'
description: 'Cache and install the go-c8y-cli binary (c8y) to $PATH'
author: reubenmiller
inputs:
  version:
    required: false
    description: go-c8y-cli version to setup
    default: latest
  showVersion:
    required: false
    description: Show cli version
    default: "true"
  showTenant:
    required: false
    description: Show tenant information
    default: "true"
  preserveStdin:
    required: false
    description: Redirect stdin to /dev/null to avoid go-c8y-cli pipeline detection as GithubRunner set stdin to a FIFO buffer
    default: "false"
runs:
  using: 'node20'
  main: 'dist/index.js'
