name: example
on:
  workflow_dispatch:

env:
  C8Y_HOST: '${{ secrets.C8Y_HOST }}'
  C8Y_USER: '${{ secrets.C8Y_USER }}'
  C8Y_PASSWORD: '${{ secrets.C8Y_PASSWORD }}'

jobs:
  job0-0:
      name: job0-ubuntu (new c8y version)
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go 1.x
          uses: actions/setup-go@v5
          with:
            go-version: "1.24"
            cache: false

        - run: |
            go install github.com/reubenmiller/go-c8y-cli/v2/cmd/c8y@d41972054e6b8a3079bb36172f93e920083882b3

        - name: No stdin check
          run: |
            c8y devices list -n

        - name: Stdin check (redirect dev null)
          run: |
            c8y devices list </dev/null

        - name: Stdin check
          run: |
            c8y devices list
        
        - name: Stdin check (piped input)
          run: |
            c8y devices list -p 1 -n | c8y devices get >/dev/null

  job0-1:
      name: job0-windows (new c8y version)
      runs-on: windows-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go 1.x
          uses: actions/setup-go@v5
          with:
            go-version: "1.24"
            cache: false

        - run: |
            go install github.com/reubenmiller/go-c8y-cli/v2/cmd/c8y@d41972054e6b8a3079bb36172f93e920083882b3

        - name: No stdin check
          run: |
            c8y devices list -n

        # skip as windows does not support this syntax
        # - name: Stdin check (redirect dev null)
        #   run: |
        #     c8y devices list </dev/null

        - name: Stdin check
          run: |
            c8y devices list

        - name: Stdin check (piped input)
          run: |
            c8y devices list -p 1 -n | c8y devices get >/dev/null
  job0-2:
      name: job0-macos (new c8y version)
      runs-on: macos-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go 1.x
          uses: actions/setup-go@v5
          with:
            go-version: "1.24"
            cache: false

        - run: |
            go install github.com/reubenmiller/go-c8y-cli/v2/cmd/c8y@d41972054e6b8a3079bb36172f93e920083882b3

        - name: No stdin check
          run: |
            c8y devices list -n

        - name: Stdin check (redirect dev null)
          run: |
            c8y devices list </dev/null

        - name: Stdin check
          run: |
            c8y devices list </dev/null
            c8y devices list

        - name: Stdin check (piped input)
          run: |
            c8y devices list -p 1 -n | c8y devices get >/dev/null

  job1:
      name: job1 (redirect stdin)
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4
        - uses: reubenmiller/setup-go-c8y-cli@feat-stdin-redirect

        - name: No stdin check
          run: |
            c8y devices list -n

        - name: Stdin check
          run: |
            exec 0</dev/null  # Redirect stdin globally
            c8y devices list

  job2:
    name: job2 (current)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: reubenmiller/setup-go-c8y-cli@main

      - name: No stdin check
        run: |
          c8y devices list -n
      - name: Stdin check
        run: |
          timeout 5 c8y devices list
