name: 'example'
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reubenmiller/setup-go-c8y-cli@main
      - run: |
          c8y version
